# Extend only the pinned tokenizer, in a build-tree copy. All llama translation
# units use the copied headers, avoiding mismatched class declarations. No TLS,
# global policy, or mutation of the read-only submodule is involved.
function(skein_tokenizer_overlay upstream output)
  set(patches "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/tokenizer-patches")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${patches}/PINS.txt")
  file(STRINGS "${patches}/PINS.txt" records)
  foreach(record IN LISTS records)
    if(record MATCHES "^#" OR record STREQUAL "")
      continue()
    endif()
    if(NOT record MATCHES "^(patch|before|after) ([0-9a-f]+) ([a-zA-Z0-9.-]+)$")
      message(FATAL_ERROR "Invalid tokenizer overlay pin")
    endif()
    set(kind "${CMAKE_MATCH_1}")
    set(want "${CMAKE_MATCH_2}")
    set(name "${CMAKE_MATCH_3}")
    string(LENGTH "${want}" hash_length)
    if(NOT hash_length EQUAL 64)
      message(FATAL_ERROR "Invalid tokenizer overlay SHA256")
    endif()
    list(APPEND ${kind}_pins "${want}=${name}")
  endforeach()
  foreach(kind patch before after)
    if(NOT ${kind}_pins)
      message(FATAL_ERROR "Missing tokenizer overlay ${kind} pins")
    endif()
  endforeach()
  foreach(kind patch before)
    foreach(pin IN LISTS ${kind}_pins)
      string(REPLACE "=" ";" parts "${pin}")
      list(GET parts 0 want)
      list(GET parts 1 name)
      if(kind STREQUAL "patch")
        set(path "${patches}/${name}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
      else()
        set(path "${upstream}/src/${name}")
      endif()
      file(SHA256 "${path}" actual)
      if(NOT actual STREQUAL want)
        message(FATAL_ERROR "Tokenizer overlay ${kind} hash mismatch: ${name}")
      endif()
    endforeach()
  endforeach()
  # COPYONLY on every configure restores pristine inputs before applying the
  # patch, even when timestamps would otherwise leave a previously patched copy.
  file(GLOB_RECURSE source_files LIST_DIRECTORIES false "${upstream}/src/*")
  foreach(source IN LISTS source_files)
    file(RELATIVE_PATH relative "${upstream}/src" "${source}")
    configure_file("${source}" "${output}/${relative}" COPYONLY)
  endforeach()
  find_program(tokenizer_patch NAMES patch REQUIRED)
  foreach(pin IN LISTS patch_pins)
    string(REPLACE "=" ";" parts "${pin}")
    list(GET parts 1 name)
    execute_process(COMMAND "${tokenizer_patch}" --batch -p1 -i "${patches}/${name}"
      WORKING_DIRECTORY "${output}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Tokenizer overlay patch failed: ${error}")
    endif()
  endforeach()
  foreach(pin IN LISTS after_pins)
    string(REPLACE "=" ";" parts "${pin}")
    list(GET parts 0 want)
    list(GET parts 1 name)
    file(SHA256 "${output}/${name}" actual)
    if(NOT actual STREQUAL want)
      message(FATAL_ERROR "Tokenizer overlay after hash mismatch: ${name}")
    endif()
  endforeach()

  # Upstream creates this target before we redirect it. Keep the include and
  # PCH source locations coherent, including model sources in unity builds.
  get_target_property(source_dir llama SOURCE_DIR)
  get_target_property(sources llama SOURCES)
  foreach(source IN LISTS sources)
    if(IS_ABSOLUTE "${source}")
      set(original "${source}")
    else()
      get_filename_component(original "${source}" ABSOLUTE BASE_DIR "${source_dir}")
    endif()
    string(FIND "${original}" "${upstream}/src/" in_source)
    if(in_source EQUAL 0)
      string(REPLACE "${upstream}/src/" "${output}/" replacement "${original}")
      list(APPEND redirected "${replacement}")
      foreach(property SKIP_UNITY_BUILD_INCLUSION SKIP_PRECOMPILE_HEADERS COMPILE_DEFINITIONS
          COMPILE_OPTIONS COMPILE_FLAGS INCLUDE_DIRECTORIES LANGUAGE OBJECT_DEPENDS)
        get_source_file_property(value "${original}" TARGET_DIRECTORY llama ${property})
        if(NOT value STREQUAL "NOTFOUND")
          set_source_files_properties("${replacement}" TARGET_DIRECTORY llama PROPERTIES ${property} "${value}")
        endif()
      endforeach()
    else()
      list(APPEND redirected "${original}")
    endif()
  endforeach()
  set_property(TARGET llama PROPERTY SOURCES "${redirected}")
  foreach(property INCLUDE_DIRECTORIES PRECOMPILE_HEADERS)
    get_target_property(values llama ${property})
    if(values STREQUAL "values-NOTFOUND")
      continue()
    endif()
    set(normalized "")
    foreach(value IN LISTS values)
      if(value MATCHES "^\\$<" OR value MATCHES "^<")
        message(FATAL_ERROR "Tokenizer overlay requires review of generated ${property}")
      endif()
      get_filename_component(value "${value}" ABSOLUTE BASE_DIR "${source_dir}")
      # Normalize ../include before matching: it belongs to the original
      # public API directory, not a nonexistent sibling of generated src.
      if(value STREQUAL "${upstream}/src")
        set(value "${output}")
      else()
        string(REPLACE "${upstream}/src/" "${output}/" value "${value}")
      endif()
      list(APPEND normalized "${value}")
    endforeach()
    set_property(TARGET llama PROPERTY ${property} "${normalized}")
  endforeach()
endfunction()
