# E1.I11 (skein-4je) — spec §9: release builds strip verbose logging.
#
# Scope decision, documented per the issue brief ("do NOT silently flip
# minify on without updating the reproducibility notes"): `isMinifyEnabled`
# was `false` for `release` before this issue (E1.I8, the dedicated
# reproducible-build/R8-full-mode issue, has not landed yet — see its ACs in
# skein-plan.json). Turning on full R8 shrinking + obfuscation here, without
# that issue's keep-rule audit across every module (Compose, kotlinx
# serialization, androidx biometric/datastore, WorkManager-to-come), risks
# breaking `assembleFossRelease` in ways this issue isn't scoped to chase
# down, and would change what the CI reproducible-build double-build compares
# (.github/workflows/reproducible-build.yml) beyond this issue's remit.
#
# So `isMinifyEnabled` is enabled (R8 must run for `-assumenosideeffects`
# below to do anything at all — AGP only invokes R8 for a minified variant),
# but scoped narrowly:
#   - `-dontobfuscate`: no renaming, so nothing here changes based on R8's
#     name-mapping/keep-rule completeness, and the reproducible-build
#     double-build has one less source of nondeterminism to worry about.
#   - the blanket `-keep`/`-keepclassmembers` below disable *shrinking* of
#     every class/member (nothing is removed for being "unreachable"), so a
#     missing keep rule for reflection (kotlinx.serialization, WorkManager,
#     androidx.datastore) cannot silently break the app.
#   - R8's *optimizer* still runs — the one behavior this issue actually
#     wants (dead code elimination applying `-assumenosideeffects` to
#     `SkeinLog.d`/`SkeinLog.i`) is an optimization, not a shrinking or
#     obfuscation step, so it fires anyway.
#
# `E1.I8` is expected to replace this file's blanket `-keep` with a real,
# audited keep-rule set and re-enable obfuscation/full shrinking as part of
# its own size-budget and reproducibility work; this file's job today is
# only AC(a) (SkeinLog.d/i absent from the release dex), verified by
# `tools/logging/check-release-dex.sh`.
-dontobfuscate
-keep class ** { *; }
-keepclassmembers class ** { *; }

-assumenosideeffects class app.skein.core.model.SkeinLog {
    public static void d(java.lang.String, java.lang.String);
    public static void i(java.lang.String, java.lang.String);
}

# Optional runtime-only references from transitive dependencies (PDFBox's
# JPEG2000 filter, Bouncy Castle's JNDI/LDAP CertStore/DANE fetchers) that
# are never reached on Android (no javax.naming, no com.gemalto.jp2 on the
# classpath) and are not part of this app's own dependency graph — this app
# never touches PDFBox's JPXFilter or Bouncy Castle's LDAP/DANE lookups.
# Generated by AGP into app/build/outputs/mapping/fossRelease/missing_rules.txt;
# copied here so `-keep class ** { *; }` above doesn't also force R8 to
# resolve them.
-dontwarn com.gemalto.jp2.JP2Decoder
-dontwarn com.gemalto.jp2.JP2Encoder
-dontwarn javax.naming.Binding
-dontwarn javax.naming.NamingEnumeration
-dontwarn javax.naming.NamingException
-dontwarn javax.naming.directory.Attribute
-dontwarn javax.naming.directory.Attributes
-dontwarn javax.naming.directory.DirContext
-dontwarn javax.naming.directory.InitialDirContext
-dontwarn javax.naming.directory.SearchControls
-dontwarn javax.naming.directory.SearchResult
