package app.skein.inference.service

import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/** Structural fixtures generated by the pinned native renderer; see resources/templating/README.md. */
class PinnedTemplateReferenceTest {
    @Test
    fun `verified layouts agree with pinned upstream renders or refuse unsupported transformations`() {
        val lines =
            javaClass.getResourceAsStream("/templating/chat-template-reference.tsv")!!.bufferedReader().use {
                it.readLines()
            }
        val fixtures = lines.filterNot { it.startsWith("#") || it.isBlank() }
        assertEquals(9, fixtures.size)
        for (line in fixtures) {
            val (name, format, roleText, contentHex, expectedHex) = line.split('\t')
            val roles = roleText.split(',').toTypedArray()
            val contents = contentHex.split(',').map(::unhex).toTypedArray()
            val expected = unhex(expectedHex)
            val backend = if (format == "chatml") FakeLlamaBackend() else GemmaRenderer()
            // Catch drift in the renderer double before using it for the boundary probe.
            assertEquals(name, expected, backend.applyChatTemplate(42L, roles, contents, true))

            if (name == "gemma-trimmed") {
                val error =
                    assertThrows(LlamaException::class.java) {
                        ChatTemplating.render(backend, 42L, roles, contents, true)
                    }
                assertEquals(LlamaErrorCode.TEMPLATE_UNSUPPORTED, error.code)
            } else {
                val result = ChatTemplating.render(backend, 42L, roles, contents, true)
                assertEquals(name, expected, result.text)
                assertEquals(name, expected, result.segments.joinToString("") { it.text })
                assertEquals(
                    name,
                    contents.filter { it.isNotEmpty() },
                    result.segments.filter { it.kind == SegmentKind.CONTENT }.map { it.text },
                )
            }
        }
    }

    private fun unhex(value: String): String =
        value
            .chunked(2)
            .map {
                it.toInt(16).toByte()
            }.toByteArray()
            .toString(Charsets.UTF_8)

    /** Mirrors the pinned Gemma branch only to provide probe renders; the independent fixtures check it above. */
    private class GemmaRenderer : FakeLlamaBackend() {
        override fun applyChatTemplate(
            model: Long,
            roles: Array<String>,
            contents: Array<String>,
            addAssistant: Boolean,
        ): String =
            buildString {
                var system = ""
                for (index in roles.indices) {
                    if (roles[index] == "system") {
                        system += contents[index].trim()
                        continue
                    }
                    val role = if (roles[index] == "assistant") "model" else roles[index]
                    append("<start_of_turn>").append(role).append('\n')
                    if (system.isNotEmpty() && role != "model") {
                        append(system).append("\n\n")
                        system = ""
                    }
                    append(contents[index].trim()).append("<end_of_turn>\n")
                }
                if (addAssistant) append("<start_of_turn>model\n")
            }
    }
}
